In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('agree100.csv', index_col = ['_unit_id'])
df

,_golden,_unit_state,_trusted_judgments,_last_judgment_at,id_rel,sentena_sem_relao,sentena_sem_relao:confidence,txt_rel,html,id_ent1,id_ent2,id_rel_gold,id_sent,id_txt,sentena_sem_relao_gold,txt_rel_gold,agree
_unit_id,,,,,,,,,,,,,,,,,
1293280368,False,finalized,3,7/5/2017 21:33:23,5 5 5,False,1.0,de de de,<span data-id='0'>A</span> <span data-id='1'>e...,7,3,NaN,S8,CIENCIA_2002_22010,NaN,,100
1293280369,False,finalized,3,7/5/2017 21:42:34,9 9 9,False,1.0,de de de,<span data-id='0'>A</span> <span data-id='1'>e...,7,10,NaN,S8,CIENCIA_2002_22010,NaN,,100
1293280370,False,golden,3,7/5/2017 20:22:38,9 9 9,False,1.0,de de de,<span data-id='0'>A</span> <span data-id='1'>e...,7,12,9.0,S8,CIENCIA_2002_22010,False,de,100
1293280371,False,finalized,3,7/6/2017 04:00:34,2 2 2,False,1.0,de de de,<span data-id='0'class='per'>Jennifer_Leonard<...,4,0,NaN,S13,CIENCIA_2002_22010,NaN,,100
1293280372,False,finalized,3,7/5/2017 20:24:52,5 5 5,False,1.0,em em em,<span data-id='0'class='entity'>Jennifer_Leona...,4,6,NaN,S13,CIENCIA_2002_22010,NaN,,100
1293280373,False,finalized,3,7/5/2017 20:24:09,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'class='entity'>Jennifer_Leona...,4,14,NaN,S13,CIENCIA_2002_22010,NaN,,100
1293280374,False,finalized,3,7/6/2017 04:22:40,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'class='entity'>Jennifer_Leona...,4,18,NaN,S13,CIENCIA_2002_22010,NaN,,100
1293280375,False,finalized,3,7/5/2017 20:22:38,"2,3 2,3 2,3",False,1.0,paleontólogo de paleontólogo de paleontólogo de,<span data-id='0'class='per'>Marcelo_Tejedor</...,5,0,NaN,S2,CIENCIA_2005_28756,NaN,,100
1293280379,False,finalized,3,7/5/2017 20:24:52,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>E...",25,37,NaN,S18,CIENCIA_2000_17113,NaN,,100
1293280381,False,finalized,3,7/6/2017 04:22:40,36 36 36,False,1.0,", , ,","<span data-id='0'>""</span> <span data-id='1'>E...",35,37,NaN,S18,CIENCIA_2000_17113,NaN,,100
1293280382,False,finalized,3,7/6/2017 04:02:00,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Depois</span> <span data-id=...,7,22,NaN,S0,CIENCIA_2003_6457,NaN,,100
1293280385,False,finalized,3,7/5/2017 20:24:09,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>O</span> <span data-id='1'>e...,11,20,NaN,S3,CIENCIA_2003_6457,NaN,,100
1293280386,False,finalized,3,7/6/2017 03:58:54,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Mas</span> <span data-id='1'...,7,10,NaN,S9,CIENCIA_2003_6457,NaN,,100
1293280387,False,finalized,3,7/5/2017 20:24:52,5 5 5,False,1.0,em em em,<span data-id='0'>Cientistas</span> <span data...,3,7,NaN,S0,CIENCIA_2001_19858,NaN,,100
1293280389,False,finalized,3,7/5/2017 20:24:09,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Um</span> <span data-id='1'>...,12,18,NaN,S0,CIENCIA_2004_6488,NaN,,100
1293280392,False,finalized,3,7/6/2017 09:24:19,17 17 17,False,1.0,( ( (,<span data-id='0'>Um</span> <span data-id='1'>...,16,18,NaN,S0,CIENCIA_2004_6488,NaN,,100
1293280394,False,finalized,3,7/5/2017 20:22:38,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Um</span> <span data-id='1'>...,16,42-45,NaN,S0,CIENCIA_2004_6488,NaN,,100
1293280398,False,finalized,3,7/5/2017 20:23:19,6 6 6,False,1.0,( ( (,<span data-id='0'>Primeiro</span> <span data-i...,5,7,NaN,S2,CIENCIA_2004_6488,NaN,,100
1293280400,False,finalized,3,7/5/2017 20:24:52,8 8 8,False,1.0,( ( (,<span data-id='0'>A</span> <span data-id='1'>i...,9-11,6-7,NaN,S1,CIENCIA_2003_24219,NaN,,100
1293280401,False,finalized,3,7/6/2017 09:24:19,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>i...,9-11,26,NaN,S1,CIENCIA_2003_24219,NaN,,100
1293280404,False,finalized,3,7/5/2017 20:23:19,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>i...,31,6-7,NaN,S1,CIENCIA_2003_24219,NaN,,100
1293280405,False,finalized,3,7/5/2017 21:42:34,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>i...,31,26,NaN,S1,CIENCIA_2003_24219,NaN,,100
1293280406,False,finalized,3,7/6/2017 04:00:34,32 32 32,False,1.0,( ( (,<span data-id='0'>A</span> <span data-id='1'>i...,31,33,NaN,S1,CIENCIA_2003_24219,NaN,,100
1293280409,False,finalized,3,7/6/2017 06:04:27,5 5 5,False,1.0,de de de,<span data-id='0'class='per'>Francelino_Grando...,7,0,NaN,S4,CIENCIA_2003_24219,NaN,,100
1293280410,False,finalized,3,7/6/2017 04:02:00,5 5 5,False,1.0,de de de,<span data-id='0'class='entity'>Francelino_Gra...,7,2-4,NaN,S4,CIENCIA_2003_24219,NaN,,100
1293280411,False,finalized,3,7/5/2017 20:23:19,8 8 8,False,1.0,( ( (,<span data-id='0'class='entity'>Francelino_Gra...,7,9,NaN,S4,CIENCIA_2003_24219,NaN,,100
1293280414,False,finalized,3,7/5/2017 20:23:19,7 7 7,False,1.0,de de de,<span data-id='0'>O</span> <span data-id='1'>p...,6,8,NaN,S15,CIENCIA_2003_24219,NaN,,100
1293280415,False,finalized,3,7/5/2017 21:33:23,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Ainda</span> <span data-id='...,10,6,NaN,S17,CIENCIA_2003_24219,NaN,,100
1293280417,False,finalized,3,7/5/2017 20:24:09,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Ainda</span> <span data-id='...,10,20,NaN,S17,CIENCIA_2003_24219,NaN,,100
1293280419,False,finalized,3,7/10/2017 23:27:35,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Ainda</span> <span data-id='...,20,8,NaN,S17,CIENCIA_2003_24219,NaN,,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293280573,False,finalized,3,7/11/2017 02:45:28,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Pesquisadores</span> <span d...,3,39,NaN,S0,CIENCIA_2001_6406,NaN,,100
1293280575,False,finalized,3,7/11/2017 17:14:31,6 6 6,False,1.0,de de de,<span data-id='0'>É</span> <span data-id='1'>o...,8,4,NaN,S4,CIENCIA_2001_6406,NaN,,100
1293280576,False,finalized,3,7/11/2017 02:31:45,9 9 9,False,1.0,( ( (,<span data-id='0'>É</span> <span data-id='1'>o...,8,10,NaN,S4,CIENCIA_2001_6406,NaN,,100
1293280577,False,finalized,3,7/10/2017 21:20:53,7 7 7,False,1.0,( ( (,<span data-id='0'>Seus</span> <span data-id='1...,6,8,NaN,S14,CIENCIA_2000_17101,NaN,,100
1293280578,False,finalized,3,7/10/2017 21:28:55,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0-3'class='entity'>Seis de as n...,11,15,NaN,S3,CIENCIA_2005_6518,NaN,,100
1293280579,False,finalized,3,7/10/2017 21:24:39,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Os</span> <span data-id='1'>...,6,18,NaN,S14,CIENCIA_2005_6518,NaN,,100
1293280580,False,finalized,3,7/10/2017 21:24:39,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Os</span> <span data-id='1'>...,6,20,NaN,S14,CIENCIA_2005_6518,NaN,,100
1293280583,False,finalized,3,7/10/2017 23:49:18,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'class='entity'>Sete</span> <s...,4,24,NaN,S0,CIENCIA_2000_6391,NaN,,100
1293280584,False,finalized,3,7/10/2017 23:36:21,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'class='entity'>Sete</span> <s...,4,31-34,NaN,S0,CIENCIA_2000_6391,NaN,,100
1293280586,False,finalized,3,7/10/2017 21:26:46,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>N...",28,22,NaN,S4,CIENCIA_2000_6391,NaN,,100
1293280587,False,finalized,3,7/11/2017 02:44:21,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>N...",28,49,NaN,S4,CIENCIA_2000_6391,NaN,,100
1293280588,False,finalized,3,7/11/2017 12:23:57,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>N...",49,22,NaN,S4,CIENCIA_2000_6391,NaN,,100
1293280589,False,finalized,3,7/10/2017 21:20:53,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>Para</span> <span data-id='1...,2,16,NaN,S6,CIENCIA_2000_6391,NaN,,100
1293280591,False,finalized,3,7/10/2017 23:34:53,7 7 7,False,1.0,de de de,<span data-id='0'>A</span> <span data-id='1'>e...,9,5,NaN,S1,CIENCIA_2004_6494,NaN,,100
1293280592,False,finalized,3,7/11/2017 02:44:21,10 10 10,False,1.0,em em em,<span data-id='0'>A</span> <span data-id='1'>e...,9,11,NaN,S1,CIENCIA_2004_6494,NaN,,100
1293280593,False,finalized,3,7/11/2017 02:37:22,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>e...,9,28,NaN,S1,CIENCIA_2004_6494,NaN,,100
1293280594,False,finalized,3,7/11/2017 03:40:41,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>e...,28,5,NaN,S1,CIENCIA_2004_6494,NaN,,100
1293280595,False,finalized,3,7/11/2017 02:33:29,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>A</span> <span data-id='1'>e...,28,11,NaN,S1,CIENCIA_2004_6494,NaN,,100
1293280596,False,finalized,3,7/10/2017 23:28:53,5 5 5,False,1.0,em em em,<span data-id='0'>Bioantropólogo</span> <span ...,3,7,NaN,S1,CIENCIA_2004_26415,NaN,,100
1293280597,False,finalized,3,7/11/2017 16:56:27,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>E...",45,13,NaN,S2,CIENCIA_2004_26415,NaN,,100
1293280598,False,finalized,3,7/10/2017 21:20:02,46 46 46,False,1.0,( ( (,"<span data-id='0'>""</span> <span data-id='1'>E...",45,47-50,NaN,S2,CIENCIA_2004_26415,NaN,,100
1293280599,False,finalized,3,7/10/2017 21:26:46,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,"<span data-id='0'>""</span> <span data-id='1'>E...",47-50,13,NaN,S2,CIENCIA_2004_26415,NaN,,100
1293280601,False,finalized,3,7/10/2017 21:28:55,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>O</span> <span data-id='1'cl...,1,36,NaN,S0,CIENCIA_2005_6515,NaN,,100
1293280602,False,finalized,3,7/11/2017 02:40:34,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>O</span> <span data-id='1'cl...,3-7,36,NaN,S0,CIENCIA_2005_6515,NaN,,100
1293280604,False,finalized,3,7/10/2017 23:38:03,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>O</span> <span data-id='1'>c...,7,16,NaN,S5,CIENCIA_2005_6515,NaN,,100
1293280605,False,finalized,3,7/10/2017 23:39:24,-1 -1 -1,True,1.0,Sentença sem relação Sentença sem relação Sent...,<span data-id='0'>O</span> <span data-id='1'>c...,7,19,NaN,S5,CIENCIA_2005_6515,NaN,,100
1293280608,False,finalized,3,7/10/2017 23:38:03,2 2 2,False,1.0,( ( (,<span data-id='0'>A</span> <span data-id='1'cl...,1,3,NaN,S9,CIENCIA_2005_6515,NaN,,100
1293280610,False,finalized,3,7/11/2017 16:56:27,"2,3 2,3 2,3",False,1.0,diretor-presidente de diretor-presidente de di...,<span data-id='0'class='per'>Clayton_Campanhol...,5,0,NaN,S3,CIENCIA_2004_6480,NaN,,100
1293280612,False,finalized,3,7/10/2017 23:32:39,26 26 26,False,1.0,de de de,"<span data-id='0'>""</span> <span data-id='1-3'...",28,24,NaN,S8,CIENCIA_2002_22023,NaN,,100
1293280613,False,finalized,3,7/10/2017 23:36:21,24 24 24,False,1.0,de de de,"<span data-id='0'>""</span> <span data-id='1'>E...",26,22,NaN,S10,CIENCIA_2002_22023,NaN,,100

In [10]:
def count(x):
    
    html = x['html']
    check = x['sentena_sem_relao']
    
    if check:
    
        dictStatus['sem relação'] += 1
        
    elif html.find('class=\'per\'') >= 0:
        
        dictStatus['org x per'] += 1
    
    elif html.find('class=\'plc\'') >= 0:
        
        dictStatus['org x plc'] += 1
    
    else: 
        
        dictStatus['org x org'] += 1
        
        
dictStatus = {'org x org': 0, 'org x per': 0, 'org x plc': 0, 'sem relação': 0}
df.apply(count,axis = 1)

print(dictStatus)

{'org x plc': 33, 'org x org': 25, 'org x per': 40, 'sem relação': 69}